version: "3"

services:
  redis:
      image: redis:alpine
      command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
      volumes:
      - ./data/redis:/data
      ports:
        - "6379:6379"
  www:
      build: .
      restart: always
      ports:
          - '80:80'
          # - '6001:6001'
      volumes:
        - ./chat:/var/www/html
      networks:
        - default
  db:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: l_chat
      MYSQL_USER: l_chat_user
      MYSQL_PASSWORD: l_chat_password
      MYSQL_ROOT_PASSWORD: l_chat_root_password
    volumes: 
      - db_data:/var/lib/mysql
    networks:
      - default
volumes:
  db_data: