version: "3"

services:
  www:
      build: .
      restart: always
      ports:
          - '80:80'
      volumes:
        - ./chat:/var/www/html
      networks:
        - default
  db:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: l_chat
      MYSQL_USER: l_chat_user
      MYSQL_PASSWORD: l_chat_password
      MYSQL_ROOT_PASSWORD: l_chat_root_password
    volumes: 
      - db_data:/var/lib/mysql
    networks:
      - default
volumes:
  db_data: